### ISSUE TITLE
[class.mem.general] `[[no_unique_address]]`, common initial sequence, layout compatibility, and trivial copyability

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/CWG#640] opened 2024-11-11 05:10 UTC
Full name of submitter (unless configured in github; will be published with the issue): Hubert Tong

Reference (section label): [class.mem.general]

Link to reflector thread (if any): N/A

Issue description:
The wording for common initial sequences allows for corresponding `[[no_unique_address]]` members with layout-compatible types that differ in trivial copyability. This is not compatible with the Itanium C++ ABI, which uses a notion of "POD" in allocating potentially-overlapping subobjects.

Observe:
```cpp
#include <type_traits>
struct A {
  A(const A &);
  int a : 24;
};
struct AA {
  int aa : 24;
};
struct B {
  A a [[no_unique_address]];
  char b;
};
struct BB {
  AA aa [[no_unique_address]];
  char bb;
};
static_assert(std::is_layout_compatible_v<A, AA>);
static_assert(std::is_standard_layout_v<B>);
static_assert(std::is_layout_compatible_v<B, BB>);  // wording says this should pass; fails with GCC and Clang on x86-64 Linux
```

https://godbolt.org/z/Tbjb1fWfr

Suggested resolution:
For the purposes of common initial sequence, require cases where `[[no_unique_address]]` has to match to also match on trivial copyability.

**Comment by frederick-vs-ja** [comment] 2024-11-11 07:30
Seems to be duplicate of CWG2759. On Itanium ABI (where `__has_cpp_attribute(no_unique_address)` is non-zero), members marked `[[no_unique_address]]` are now excluded from common initial sequences.

> This is not compatible with the Itanium C++ ABI, which uses a notion of "POD" in allocating potentially-overlapping subobjects.

FWIW, just being standard-layout and trivially copyable (or even being trivial or C++11 POD) isn't sufficient to make the type "POD for the purpose of layout".

**Comment by jensmaurer** [comment] 2024-11-11 15:45
Agreed. We exclude any member declared with `[[no_unique_address]]` from a common initial sequence, which seems to address the concern expressed in this issue.

**Closed by jensmaurer** 2024-11-11 15:45 UTC
