### ISSUE TITLE
[class.ctor] It is not clear whether the change in p1787r6 to class.dtor and class.ctor are defect reports for the old standards

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#145] opened 2022-10-03 13:48 UTC
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [class.dtor]

Link to reflector thread (if any): https://stackoverflow.com/questions/73928601/clang-accepts-out-of-class-destructor-definition-while-gcc-does-not

Issue description: It is not clear whether the change done in [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) is a defect report for the old standards. 

I noticed that [class.dtor#1.2](https://timsong-cpp.github.io/cppwp/n4861/class.dtor#1.2) was changed from:

> in a declaration at namespace scope or in a friend declaration, the _id-expression_ is `nested-name-specifier ~class-name` and the class-name names the same class as the nested-name-specifier.

to [this](https://eel.is/c++draft/class.dtor#1.2):

> otherwise, the id-expression is nested-name-specifier ~class-name and the class-name is the injected-class-name of the class nominated by the nested-name-specifier.

This was done using [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor).

In case [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) is not a defect report for the old standards, it would mean that the following code is valid in c++20 and older standard:

```
template<typename T>
struct C
{
    ~C(); 
};

//In case p1787r6-class.dtor is not a defect report for old standards, it would mean that these next lines are valid in c++17 and c++20
template<typename T>
C<T>::~C<T>()           //implementation divergence here: many compilers allow this in c++17 and c++20 which i think was not the standard's intention
{
    
}
int main()
{
    C<int> c;;
}
```
We observe [implementation divergence](https://godbolt.org/z/b8rWrK4zr) for the above shown code. 

But I think [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) should be a DR for older standards(if not already) because the intention was already there for the above code to be invalid from the beginning. I can think of atleast two such intentions described below. 

<h4>Reason 1</h4>

Reason 1 for why [p1787-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) should be a defect report for old standards(including c++1&) is because a destructor of a class template is an ordinary(non-template) member function like other non-template member functions of that class template. And when providing an out-of-class definition for a nontemplate member function of a class template, we're not allowed to write `template<typename T>C<T>::memberName<T>(){}`. So, in this respect the destructor is no different from the nontemplate member function named `memberName` of a class template named `C`.

<h4>Reason 2</h4>

The second reason for why [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) should be a defect report for old standards(including C++17) is that while all the compilers seem to accept the out-of-class definition for destructors, they reject the same for constructors. For example, the following code is rejected by all compilers:

```
template<typename T>
struct C 
{
    C();
};
template<typename T>
C<T>::C<T>()         //ctor: rejected by all as opposed to dtor in c++17
{

}
int main()
{
    C<int> c;
}
``` 
This means that compilers are inconsistent in their behavior because while they allow the dtor  `C<T>::~C<T>()` in C++17 but at the same time they reject the ctor `C<T>::C<T>()`. [Demo](https://godbolt.org/z/rsWoasWTj).

<h4>Reason 3</h4>

Reason 3 is more of  a confirmation to why i think [this](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) should be a DR for old standard. In particular, in his talk titile: [Back to Basics: Function and Class Templates - Dan Saks - CppCon 2019](https://youtu.be/LMP_sxOaz6g?t=1631), **Dan Saks** explained that we're not allowed to write `template<typename T>C<T>~C<T>(){}` even in older standards. So i think the intention was already there in the old standards for `template<typename T> C<T>~C<T>(){}` to be invalid and which were resolved by  [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor).

<h3>Suggested resolution:</h3>

It should be cleared whether  [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) is a DR for older standards or not. That is, whether writing `template<typename T>C<T>~C<T>(){}` is invalid in C++17 and C++20 by using [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) or not. Same goes for ctor out of class definition like `template<typename T>C<T>C<T>(){}` which currently all compilers [reject](https://godbolt.org/z/rsWoasWTj) in C++17 as opposed to destructors which they [accept](https://godbolt.org/z/4GzodWdMW) in C++17.

That is, it is important to note that while all compilers [allow](https://godbolt.org/z/4GzodWdMW) the out of class definition for dtor `C<T>::~C<T>(){}` in C++17, they all [reject](https://godbolt.org/z/WzTcv8szh) the out of class definition for ctor `C<T>::C<T>(){}`. **This is a serious problem/defect and inconsistent behavior** and so I think that the changes done in [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) and [p1787r6-class.ctor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.ctor) should be applied to the older standards(including C++17).

**Comment by frederick-vs-ja** [comment] 2022-10-04 04:02
I think this has been clarified, at least for whether it is a DR against C++20. [P1787r6-class.dtor](https://wg21.link/p1787r6#class.dtor) resolved CWG399, and such resolution is a DR (per [N4864](https://wg21.link/n4884)).

However, the status for C++17 and previous revisions is confusing to me. The changes in [P1787r6-class.dtor](https://wg21.link/p1787r6#class.ctor) and [P1787r6-class.dtor](https://wg21.link/p1787r6#class.dtor) look like a follow-up changes of CWG2237, which is intentionally not a DR (also mentioned in [N4732](https://wg21.link/n4732)).

**Comment by ranaanoop** [comment] 2022-10-06 09:14
It is important to note that while all compilers allow the out of class definition for dtor `C<T>::~C<T>(){}` in C++17, they all reject the out of class definition for ctor `C<T>::C<T>(){}`. [Demo](https://godbolt.org/z/rsWoasWTj). This is a serious problem/defect and so I think that the changes done in [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) and [p1787r6-class.ctor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.ctor) should be apply to the older standards(including C++17).

**Comment by jensmaurer** [comment] 2022-10-06 22:12
Older standards have been superseded by newer ones and thus are no longer active in any shape or form. In particular, we can't accept defect reports against older standards.

WG21 does offer an opinion whether some change should be considered a defect relative to the previous standard by stating its intent that the change would be included in a Technical Corrigendum, if such were issued, by designating issues as DRs. However, it is up to implementers how far back such DRs are applied to older standard modes.

The only consistent reading of the paper trail is that CWG2237 is a change (not a DR) released with C++20, and [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) applies as a defect against C++20 and that issue (but not further back).

However, implementers appear to apply CWG2237 to older modes, so it seems reasonable for them to also apply [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) to older modes. Please discuss this with your implementation vendor, who might wish to initiate a discussion on the committee-internal reflector.

**Comment by ranaanoop** [comment] 2022-10-07 11:22
@jensmaurer Ok, so what i've understood from this discussion is that it is upto the implementators whether to apply [p1787r6-class.dtor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.dtor) and [p1787r6-class.ctor](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html#class.ctor) to older standards(like C++17). 

But I'm still surprised to see that all compilers [reject](https://godbolt.org/z/11vGahYeb) `C<T>::C<T>` but [accept](https://godbolt.org/z/4GzodWdMW) `C<T>::~C<T>`. I mean this seems like inconsistent behavior from implementation side. Anyways, as it has been clarified that this is now an implementation issue and new DRs against older standard(like c++17) can't be accepted so I'll contact the respective implementaors for any further queries. 

Thanks for the clarification. I t

**Closed** 2022-10-07 11:23 UTC
